In [1]:
pip install pandas==1.0.3

Requirement already satisfied: pandas==1.0.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.0.3)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas==1.0.3) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas==1.0.3) (1.17.4)
Requirement already satisfied: python-dateutil>=2.6.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas==1.0.3) (2.8.1)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas==1.0.3) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import pickle

%matplotlib inline
import matplotlib.pyplot as plt

# Read data from disk

In [3]:
house_prices_reg = pd.read_csv('../Datasets/boston_house_prices_regression.csv')
house_prices_reg.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,y
0,0.04981,21.0,5.64,0.0,0.439,5.998,21.4,6.8147,4.0,243.0,16.8,396.90,8.43,-1.0,22.507577,27.08,19.40,23.4
1,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,-1.0,16.238796,17.46,16.55,8.1
2,0.11329,30.0,4.93,0.0,0.428,6.897,54.3,6.3361,6.0,300.0,16.6,391.25,11.38,-1.0,27.423950,21.84,28.20,22.0
3,19.60910,0.0,18.10,0.0,0.671,7.313,97.9,1.3163,24.0,666.0,20.2,396.90,13.44,-1.0,20.939772,10.50,28.20,15.0
4,25.94060,0.0,18.10,0.0,0.679,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64,-1.0,11.319594,14.70,10.20,10.4

# Load the models required for this notebook

In [4]:
with open('../../Chapter06/Saved Models/stacked_linear_regression.pkl', 'rb') as f:
    reg = pickle.load(f)

# Calculating MAE & RMSE

In [5]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from math import sqrt

In [6]:
X = house_prices_reg.drop(columns=['y'])
y = house_prices_reg['y'].values

y_pred = reg.predict(X)

In [7]:
print('Mean Absolute Error = {}'.format(mean_absolute_error(y, y_pred)))
print('Root Mean Squared Error = {}'.format(sqrt(mean_squared_error(y, y_pred))))
print('R Squared Score = {}'.format(r2_score(y, y_pred)))

Mean Absolute Error = 2.8740843439397086
Root Mean Squared Error = 4.504583979080906
R Squared Score = 0.7634986504091825